### ISSUE TITLE
Aidon 6534

### ISSUE THREAD

**Issue by Zuru1** [HenrikSolver/picowhanport#7]
Hi! 

Has anyone used this with an Aidon 6534 meter?
I have followed the build instructions in constructing the reader but not getting any data at all.
Using a multimeter does show that everything is connected per design.

Thank you!

**Comment by gurka** [comment]
Not sure if this is applicable to you, but we have an Aidon 6534 where it says "RF500" at the port instead of "RJ12" like on this image:  ![Aidon-6534-front-right-small-72](https://github.com/user-attachments/assets/17990efd-8329-484a-bb7a-c0fd5ebe8607)

I contacted the power company (Skellefteå Kraft) to ask about this and they said that this device supports both the DLMS/COSEM EFS-profile as well as the ASCII-based EFS2-profile. If you enable the port via Skellefteå Kraft's Mina Sidor the former one (DLMS/COSEM) will be enabled. To enable the ASCII EFS2-profile you need to contact them as they have do it manually.

So, you might want to contact your power company and see whether or not it's using the EFS2-profile, and if it's possible to switch to it if it's not.

I haven't tested it yet as I'm waiting for all hardware to arrive.

**Comment by gurka** [comment]
> I haven't tested it yet as I'm waiting for all hardware to arrive.

I have now tested this software against an Aidon 6534 and it works great. As I wrote in my previous comment, you might want to double check with your power company whether they enabled the DLMS/COSEM EFS-profile or the ASCII-based EFS2-profile.

**Comment by Zuru1** [comment]
Sorry for the late reply, I did finally get it to work.
Thank you for all the help.
